version: 2
jobs:
  build:
    docker:
      - image: node:12.16.2
      - image: selenium/standalone-chrome:3.1.0
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: apt-get update
      - run: apt-get install sudo
      - run: sudo apt-get install -y openjdk-8-jdk
      - run: java -version
      - run: yarn test
      - run: yarn e2e
